# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7c918ed38ba6b4863ae55a2ebc32d93bd7de002ee6be56a9b7bf4836984d780eb5f413a9511d0760bcffa6fdf40fe6d3ec8eba556d94aa6d1a9f4bec3ecbc2

test:
  secret_key_base: 8941273aa1ecb8b802b8916c004ed4decc82991aecda190c4bcc287617fdbe4a39a34dfaa9adb84d651acbf05122d9f48115aa9d0e4c96e08c8fdf0f6b13d94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
